/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IGaugeFactoryInterface extends utils.Interface {
  functions: {
    "createGauge(address,address,address,address,address,address,bool)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "createGauge"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createGauge",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createGauge",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IGaugeFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGaugeFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createGauge(
      _rewardToken: PromiseOrValue<string>,
      _ve: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _distribution: PromiseOrValue<string>,
      _internal_bribe: PromiseOrValue<string>,
      _external_bribe: PromiseOrValue<string>,
      _isPair: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createGauge(
    _rewardToken: PromiseOrValue<string>,
    _ve: PromiseOrValue<string>,
    _token: PromiseOrValue<string>,
    _distribution: PromiseOrValue<string>,
    _internal_bribe: PromiseOrValue<string>,
    _external_bribe: PromiseOrValue<string>,
    _isPair: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createGauge(
      _rewardToken: PromiseOrValue<string>,
      _ve: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _distribution: PromiseOrValue<string>,
      _internal_bribe: PromiseOrValue<string>,
      _external_bribe: PromiseOrValue<string>,
      _isPair: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createGauge(
      _rewardToken: PromiseOrValue<string>,
      _ve: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _distribution: PromiseOrValue<string>,
      _internal_bribe: PromiseOrValue<string>,
      _external_bribe: PromiseOrValue<string>,
      _isPair: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createGauge(
      _rewardToken: PromiseOrValue<string>,
      _ve: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _distribution: PromiseOrValue<string>,
      _internal_bribe: PromiseOrValue<string>,
      _external_bribe: PromiseOrValue<string>,
      _isPair: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
