/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as veNftapiSol from "./veNFTAPI.sol";
export type { veNftapiSol };
export type { PairAPI } from "./PairAPI";
export type { RewardAPI } from "./RewardAPI";
